mitm:
  host: 127.0.0.1
  port: 8080

webdriver:
  headless: False
  use: chrome
  edge:
    bin: msedgedriver.exe
  chrome:
    bin: ~/setup/chrome/chromedriver/chromedriver
    no_sandbox: True
    user_data_dir: ~/output/douyin_web_live/douyin_selenium

output:
  # 支持
  # - xml
  # - debug
  # 两种形式
  use: []
  xml:
    save_path: ~/output/douyin_web_live/subtitles
    file_pattern: /{room_id}_{ts}.xml
  debug:
    save_path:
      error: ~/output/douyin_web_live/log/error
      unknown: ~/output/douyin_web_live/log/debug
      known: False
  video:
    save_path: ~/output/douyin_web_live/live
    file_prefix: ''
live:
  rooms:
    - ""
  users:
    # - "MS4wLjABAAAAqqJWUXfl14OZztg_Ixn9g2vtI4RsKZzTagl6bOjyL20"
    # - "MS4wLjABAAAA89SmSpUVzt1MNDUdKJnRj4V_SpQYT9A7vfn6xOPuhI6ReW6yXpQYpXiL02l5kLaU"
    # 平老师深层动力育儿学
    - MS4wLjABAAAAASwv6hRZg6nhloy9k5GVsqd--Sh4E1whTh6fc8E7X2M
    # 老唐谈育儿
    # - MS4wLjABAAAAXhJFSqRbOwRj72VtO4aFz7UEIGemZRmP9GjcoRZKgic
    #MS4wLjABAAAA_BNHk7z-Cb6siiuXuGb068BrWZP0y303EoMyXlFPhdVGozhlm836OvGEERpe9DAt
    # 杨博士讲健康
    - MS4wLjABAAAAFwP4ObHPz3u-MU9hQ8NOFav0tBdhMt6HiBgGtEsTqVZymHqN4aZl_syHED4zbrch
    # 正熙Vimber
    # - MS4wLjABAAAARBpvgOeWNAUMrvZ3x1lExSa_FvFIjaBPgG5Ttr-XM9GT7Zc_92Z9dcPv0wOOEwdW
    # 晓光谈心理
    # - MS4wLjABAAAADg7lO8bfhLPMT2o98I2iKICL_NbK8MiAwJWYbgZuKSg
    # 素老虎
    # - MS4wLjABAAAAEtWjo3mpoqV43lfn1h5_np_h4NQIjmMQcjRv7c_wbIE
    # 家师卫道
    - MS4wLjABAAAAU2jY6EbVxGVhrBsiJZAQW9Hg6rhOceFE4kdMMaS6YUmwX5gLl5yAujY7jlmMkL8l
    # 车主明
    # - MS4wLjABAAAA-dNYW4hbo72DdGqYcwvDBho-s_zYv-KB-5TWp91RS3A

api:
  userinfo: 'https://live.douyin.com/webcast/user/?aid=6383&target_uid='

